export const MODEL_INFO = {
  name: "LightGBM v3.3.5",
  version: "2.1.0",
  trainedAt: "2025-12-15T08:30:00Z",
  lastUpdated: "2026-01-20T14:15:00Z",
  algorithm: "LightGBM (Gradient Boosting Decision Trees)",
  trainingRecords: 2_247_680,
  dataSource: "Regional grid telemetry — hourly intervals, Jan 2023 – Dec 2025",
  features: [
    "hour_of_day",
    "day_of_week",
    "month",
    "temperature_celsius",
    "solar_irradiance_wm2",
    "wind_speed_ms",
    "historical_load_1h",
    "historical_load_24h",
    "is_holiday",
    "cloud_cover_pct",
  ],
  hyperparameters: {
    num_leaves: 127,
    learning_rate: 0.05,
    n_estimators: 1200,
    max_depth: 8,
    min_child_samples: 20,
    subsample: 0.85,
    colsample_bytree: 0.9,
    reg_alpha: 0.1,
    reg_lambda: 0.15,
  },
  metrics: {
    r2_demand: 0.943,
    rmse_demand: 18.7,
    mae_demand: 12.4,
    r2_price: 0.891,
    rmse_price: 0.008,
    mape_price: 4.2,
  },
  crossValidation: "5-fold temporal CV (no data leakage)",
}
